// swift-tools-version: 5.9
import PackageDescription

// NOTE: This file is regenerated by `cap sync ios` and then patched by
// scripts/fix-ios-package-swift.js (runs as the `capacitor:sync:after` hook).
// - Plugin packages reference symlinks/ (Xcode-friendly stable paths).
// - capacitor-swift-pm is resolved from the local vendor/ directory so Xcode
//   never needs to download binary XCFrameworks from GitHub.
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "CapApp-SPM",
            targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(name: "capacitor-swift-pm", path: "vendor/capacitor-swift-pm"),
        .package(name: "CapacitorCommunityCameraPreview", path: "symlinks/CapacitorCommunityCameraPreview"),
        .package(name: "CapacitorCamera", path: "symlinks/CapacitorCamera"),
        .package(name: "CapacitorGeolocation", path: "symlinks/CapacitorGeolocation")
    ],
    targets: [
        .target(
            name: "CapApp-SPM",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm"),
                .product(name: "CapacitorCommunityCameraPreview", package: "CapacitorCommunityCameraPreview"),
                .product(name: "CapacitorCamera", package: "CapacitorCamera"),
                .product(name: "CapacitorGeolocation", package: "CapacitorGeolocation")
            ]
        )
    ]
)
